### ISSUE TITLE
楼主这个项目框架的动态面包屑该怎么设置呢，我看了下代码不太好设置，楼主有好的解决思路么

### ISSUE THREAD

**Issue by xinyueyijiu** [wangyupo/v3s#3]

**Comment by wangyupo** [comment]
嗯，你把你的业务场景，组织一下发出来，我看下。

或者你看下这个是不是你想要的动态面包屑效果：[示例-v3s动态设置面包屑](https://wangyupo.github.io/v3s-admin/#/examplePage/pageAlias)。这是实现动态面包屑的 [示例代码](https://github.com/wangyupo/v3s/blob/main/src/views/aExample/examplePage/pageAlias/index.vue#L20)，使用 onBeforeRouteLeave 在离开当前页面时，判断目标路由，然后动态设置目标路由 meta 的 alias 属性即可 [动态设置路由别名](https://github.com/wangyupo/v3s/blob/main/src/router/index.js#L104)，面包屑会优先显示别名，且刷新页面不失效。

_注意：一定要判断 [目标路由](https://github.com/wangyupo/v3s/blob/main/src/views/aExample/examplePage/pageAlias/index.vue#L19) 后，再设置 meta 的 alias 属性，否则会导致跳转其它页面也会设置别名。_

**Comment by xinyueyijiu** [comment]
好的，多谢啦
